vector testing support - restructured branch for easier PR reviews
nosqlbench/nosqlbench pull request #1416
Opened 2023-07-25 16:55 UTC by jshook

This includes several commits which have been generally grouped thematically. It will make review easier if you select which commit you want to look at individually during review.

2023-07-26 13:48 UTC, jeffbanks requested changes
Overall looks good.  I will pull in the `evalcontext` additions (Groovy*) to understand that a bit more.  I suspect we will need some complementing docs.  Just a few suggestions for changes/corrections.

2023-07-26 13:48 UTC, jeffbanks commented on adapters-api/src/main/java/io/nosqlbench/adapters/api/evalcontext/GroovyCycleFunction.java
> +    private final static Logger logger = LogManager.getLogger(GroovyBooleanCycleFunction.class);
Logging class should be corrected.

2023-07-26 13:48 UTC, jeffbanks commented on adapters-api/src/test/java/io/nosqlbench/adapters/api/evalcontext/GroovyBooleanCycleFunctionTest.java
> +        System.out.println(function);
Consider removing sysout.

2023-08-16 21:11 UTC, jshook commented on adapters-api/src/main/java/io/nosqlbench/adapters/api/activityconfig/rawyaml/RawOpDef.java
> +//                setOp(new LinkedHashMap<String,Object>(Map.of("stmt",s.toString())));
replacing the logic, but the comment is cruft

2023-08-16 21:12 UTC, jshook commented on adapters-api/src/main/java/io/nosqlbench/adapters/api/activityconfig/rawyaml/RawOpDef.java
> +                    logger.warn("Used implied stmt field under name '" + keyName + "'. You can just use 'stmt: ... "+ s +"' or the equivalent to avoid this warning.");
agreed in general, this is a low-frequency high-visibility line, so not going to force it for now

2023-08-16 21:51 UTC, jshook commented on adapters-api/src/main/java/io/nosqlbench/adapters/api/evalcontext/GroovyCycleFunction.java
> +    private final static Logger logger = LogManager.getLogger(GroovyBooleanCycleFunction.class);
good catch

2023-08-16 21:55 UTC, jshook commented on adapters-api/src/test/java/io/nosqlbench/adapters/api/evalcontext/GroovyBooleanCycleFunctionTest.java
> +        System.out.println(function);
good catch

2023-08-16 22:17 UTC, jshook commented on adapter-pinecone/src/main/java/io/nosqlbench/adapter/pinecone/ops/PineconeDeleteOp.java
> +        return response;
good catch

2023-08-16 22:19 UTC, jshook commented on adapter-pinecone/src/main/resources/activities/pinecone-verify.yaml
> +#  main-write:
leaving as-is for now

2023-08-16 22:22 UTC, jshook commented on adapter-cqld4/src/main/java/io/nosqlbench/datamappers/functions/geometry/NormalizeCqlVector.java
> +            accumulator+=vals[i]*vals[i];
this is likely a bug

2023-08-16 22:22 UTC, jshook commented on adapter-cqld4/src/main/java/io/nosqlbench/datamappers/functions/geometry/NormalizeCqlVector.java
> +            accumulator+=vals[i]*vals[i];
The streaming call below replaces the accumulator

2023-08-16 22:37 UTC, MarkWolters approved these changes
Reviewed online w/Shooky, looks good!

2023-08-16 22:38 UTC, merged