Added to check if the driver is invalid
nosqlbench/nosqlbench pull request #1933
Opened 2024-04-26 11:07 UTC by workdone0

Description
Warn the user if the provided driver is not recognized, before op template resolution
Issue : https://github.com/nosqlbench/nosqlbench/issues/1006

2024-04-26 17:08 UTC, msmygit commented
Thank you @workdone0 for the contribution. Will you also be adding in a unit test on this pr?

2024-04-29 11:19 UTC, workdone0 commented
@msmygit I've incorporated the [Unit Test](https://github.com/cognitree/nosqlbench/pull/8/files) into this pull request. Additionally, I've made some modifications to the test as the previous version was incorrect.

2024-04-29 16:57 UTC, msmygit submitted a review, later dismissed
lgtm

2024-05-01 17:03 UTC, jshook requested changes
Just a minor structural change requested, otherwise looks good.

2024-05-07 19:34 UTC, workdone0 commented on nb-engine/nb-engine-cli/src/main/java/io/nosqlbench/engine/cli/NBCLI.java
> +
@jshook I moved the logic to an adjacent class but it seems like some test are failing. I reviewed the code it looks fine, do you have any suggestions or should I revert the changes.

2024-05-10 21:30 UTC, jshook commented
closes #1006

2024-05-10 21:31 UTC, jshook approved these changes
LGTM

2024-05-10 21:32 UTC, jshook requested changes
Let me take a closer look before merging this one

2024-07-10 16:58 UTC, dave2wave requested changes
Loading a driver adaptor early may lead to unexpected side effects.

This improvement should check to see if the driver adaptor exists without actually loading the driver adaptor.

2024-07-21 00:45 UTC, dave2wave commented
There is something else going on with some adaptors due to our builds. We need to discuss (#1989) and adjust this PR accordingly.

2024-07-29 00:37 UTC, dave2wave approved these changes

2024-07-29 00:44 UTC, dave2wave commented
The known, but missing adapter situation needs to be handled as a separate issue. See #2001

2024-10-02 20:06 UTC, jshook approved these changes
I thought there were pending issues with this, but after an other review, the changes seem specific enough not to cause concern.

2024-10-02 20:06 UTC, merged