TextOfFile Binding for HTTP Scenarios (#975)
nosqlbench/nosqlbench pull request #985
Opened 2023-02-03 21:50 UTC by jeffbanks

**Includes:**
* Capabilities for #975. 
* A new `TextOfFile()` binding for use with http rest scenarios.
* Updates to `dynamodb` scenarios.
* Includes support for externalized tokens referenced by scenarios.

2023-02-03 23:29 UTC, jshook commented on adapter-http/src/main/resources/activities/baselines/http-rest-keyvalue.yaml
> +  request_token: ToString(); TextOfFile("data/stargate_token.txt");
It would be nice to allow this file to change, as `TextOfFile("TEMPLATE(stargate_tokenfile,data/stargate_token.txt)")`

2023-02-03 23:30 UTC, jshook commented on adapter-http/src/main/resources/activities/baselines/http-rest-timeseries.yaml
> +  auth_token: my_auth_token "b8571dd5-a084-4b03-96e7-47d565972f75"
this should be removed

2023-02-03 23:31 UTC, jshook commented on virtdata-lib-basics/src/main/java/io/nosqlbench/virtdata/library/basics/shared/unary_string/TextOfFile.java
> +        return lines.get(0);
We should pre-process this in the ctor, and only keep the output String.

2023-02-03 23:32 UTC, jshook requested changes
Just some minor requests before merge

2023-02-05 00:53 UTC, jeffbanks commented on adapter-http/src/main/resources/activities/baselines/http-rest-timeseries.yaml
> +  auth_token: my_auth_token "b8571dd5-a084-4b03-96e7-47d565972f75"
A test token, removed now.

2023-02-06 02:23 UTC, jshook commented on virtdata-lib-basics/src/main/java/io/nosqlbench/virtdata/library/basics/shared/unary_string/TextOfFile.java
> +        return text;
nice!

2023-02-06 02:23 UTC, jshook approved these changes

2023-02-06 02:23 UTC, merged